# Generated by Django 5.2.8 on 2026-09-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_purchaseorder_received_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='confirmed_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
